const $=s=>document.querySelector(s);let cars=JSON.parse(localStorage.getItem('hwCars')||'[]'),photo='',selected=null,stream=null;
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function render(){let q=$('#search').value.toLowerCase().trim();let a=cars.filter(x=>[x.name,x.series,x.year,x.number,x.notes].join(' ').toLowerCase().includes(q));$('#count').textContent=cars.length;$('#grid').innerHTML=a.map(x=>`<article class="card" data-id="${x.id}"><img src="${x.photo}" alt="${esc(x.name)}"><div class="ci"><div class="ct">${esc(x.name||'Unnamed')}</div><div class="cm">${esc([x.series,x.year].filter(Boolean).join(' • '))}</div></div></article>`).join('');$('#empty').style.display=cars.length?'none':'block';document.querySelectorAll('.card').forEach(c=>c.onclick=()=>details(c.dataset.id))}
function save(){localStorage.setItem('hwCars',JSON.stringify(cars));render()}function modal(id,on=true){$('#'+id).classList.toggle('hidden',!on)}function msg(s){let t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1600)}
async function scan(){modal('scanner');try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});$('#video').srcObject=stream}catch(e){$('#camMsg').textContent='Camera access unavailable. Use Choose Photo instead.'}}
function stop(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}$('#video').srcObject=null}
function review(data){photo=data;stop();modal('scanner',false);$('#preview').src=data;$('#year').value=new Date().getFullYear();['name','series','number','notes'].forEach(id=>$('#'+id).value='');modal('review')}
$('#scanTop').onclick=scan;$('#scanEmpty').onclick=scan;$('#scanNav').onclick=scan;$('#search').oninput=render;document.querySelectorAll('.close').forEach(x=>x.onclick=()=>{modal(x.closest('.sheet').id,false);stop()});
$('#capture').onclick=()=>{let v=$('#video'),c=$('#canvas');if(!v.videoWidth)return msg('Camera is not ready');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);review(c.toDataURL('image/jpeg',.88))};
$('#file').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>review(r.result);r.readAsDataURL(f)};
$('#save').onclick=()=>{cars.unshift({id:crypto.randomUUID?crypto.randomUUID():Date.now(),photo,name:$('#name').value.trim()||'Unnamed Hot Wheels',series:$('#series').value.trim(),year:$('#year').value.trim(),number:$('#number').value.trim(),notes:$('#notes').value.trim(),createdAt:Date.now()});save();modal('review',false);msg('Added to collection')};
function details(id){selected=cars.find(x=>String(x.id)===String(id));if(!selected)return;$('#dname').textContent=selected.name;$('#dphoto').src=selected.photo;$('#dmeta').textContent=[selected.series,selected.year,selected.number].filter(Boolean).join(' • ');$('#dnotes').textContent=selected.notes||'No notes.';modal('detail')}
$('#remove').onclick=()=>{cars=cars.filter(x=>x!==selected);save();modal('detail',false);msg('Removed from collection')};$('#sort').onclick=()=>{cars.reverse();save()};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});render();
